SplineFontDB: 3.2
FontName: Wislandic
FullName: Wislandic
FamilyName: Wislandic
Weight: Regular
Copyright: Copyright (c) 2026, Mekelaina/Azura Akumore/Chloe Hausser
UComments: "2026-1-18: Created with FontForge (http://fontforge.org)"
Version: 001.000
ItalicAngle: -6.2
UnderlinePosition: -102.4
UnderlineWidth: 51.2
Ascent: 819
Descent: 205
InvalidEm: 0
LayerCount: 2
Layer: 0 0 "Back" 1
Layer: 1 0 "Fore" 0
XUID: [1021 314 182952463 7594334]
StyleMap: 0x0000
FSType: 0
OS2Version: 0
OS2_WeightWidthSlopeOnly: 0
OS2_UseTypoMetrics: 1
CreationTime: 1768761821
ModificationTime: 1769097980
OS2TypoAscent: 0
OS2TypoAOffset: 1
OS2TypoDescent: 0
OS2TypoDOffset: 1
OS2TypoLinegap: 92
OS2WinAscent: 0
OS2WinAOffset: 1
OS2WinDescent: 0
OS2WinDOffset: 1
HheadAscent: 0
HheadAOffset: 1
HheadDescent: 0
HheadDOffset: 1
Lookup: 4 0 1 "'liga' Standard Ligatures in Latin lookup 0" { "'liga' Standard Ligatures in Latin lookup 0-1"  } ['liga' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
Lookup: 258 0 0 "'kern' Horizontal Kerning in Latin lookup 0" { "'kern' Horizontal Kerning in Latin lookup 0-1" [80,8,2] } ['kern' ('DFLT' <'dflt' > 'latn' <'dflt' > ) ]
MarkAttachClasses: 1
DEI: 91125
Encoding: ISO8859-1
UnicodeInterp: none
NameList: AGL For New Fonts
DisplaySize: -48
AntiAlias: 1
FitToEm: 0
WidthSeparation: 50
WinInfo: 64 16 4
BeginPrivate: 0
EndPrivate
Grid
-12.2880859375 -61.4404296875 m 7
 -8.1923828125 -61.4404296875 1106.94433594 -61.4404296875 1111.04003906 -61.4404296875 c 1028
NamedP: "Number Base"
-17.408203125 583.6796875 m 3
 -13.3115234375 583.6796875 1101.82421875 583.6796875 1105.91992188 583.6796875 c 1024
-17.408203125 716.799804688 m 3
 -13.3115234375 716.799804688 1101.82421875 716.799804688 1105.91992188 716.799804688 c 1024
-12.2880859375 204.799804688 m 3
 -8.1923828125 204.799804688 1106.94433594 204.799804688 1111.04003906 204.799804688 c 1024
NamedP: "Number Base"
EndSplineSet
TeXData: 1 0 0 209715 104857 69905 601516 1048576 69905 783286 444596 497025 792723 393216 433062 380633 303038 157286 324010 404750 52429 2506097 1059062 262144
EndSplineFont
